// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const url =
  process.env.NODE_ENV === "test"
    ? process.env.TEST_PG_STRING
    : process.env.PG_STRING;

if (!url) {
  throw new Error("The connection string is missing!");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
