name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Generate Prisma Client
        working-directory: ./backend
        env:
          NODE_ENV: test
          TEST_PG_STRING: ${{ secrets.TEST_PG_STRING }}
        run: npx prisma generate

      - name: Run backend tests
        working-directory: ./backend
        env:
          TEST_PG_STRING: ${{ secrets.TEST_PG_STRING }}
        run: npx vitest run

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      - name: Build docker image
        run: docker build -t stock-core-backend ./backend
        